[tool.mypy]
exclude = ["tests"]

[tool.ruff]
extend-exclude = ["**/tests"]

[tool.ruff.lint]
select = [
    "I",   # isort
    "E",   # pycodestyle
    "W",   # pycodestyle
    "F",   # Pyflakes
    "PL",  # Pylint
    "UP",  # pyupgrad
]
ignore = [
    "PLR0911",  # Too many return statements
]
